spring:
  application:
    name: goal-tracker-demo
  freemarker:
    template-loader-path: classpath:templates
    suffix: .ftl
  datasource:
    url: jdbc:postgresql://localhost:5432/goal_tracker_db
    username: postgres
    password: 0987
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect