spring:
  application:
    name: goal-tracker-demo
  freemarker:
    template-loader-path: classpath:templates
    suffix: .ftl
  datasource:
    url: jdbc:postgresql://localhost:5432/goal_tracker_db_demo
    username: postgres
    password: 0987
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    out-of-order: true
    enabled: true
    locations: classpath:db/migration
#    url: jdbc:postgresql://localhost:5432/goal_tracker_db_demo
#    user: postgres
#    password: 0987