name: Deploy to AWS

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java & Checkstyle
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Run Java Linter
        run: |
          chmod +x backend/gradlew
          cd backend
          ./gradlew checkstyleMain
        continue-on-error: true

      - name: Setup Node & ESLint
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Run Angular Linter
        run: |
          cd frontend
          npm ci --legacy-peer-deps
          npm run lint
        continue-on-error: true


  deploy:
    needs: build 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Connect to EC2 and Run Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/habit-tracker-dreamdeck-demo
            chmod +x rerun.sh
            ./rerun.sh


  deploy-ecr:
    needs: deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Verify Install
        run: |
          echo "AWS CLI Version:"
          aws --version
          echo "Terraform Version:"
          terraform --version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false